# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'krlApp.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1160, 952)
        MainWindow.setStyleSheet("QWidget#centralwidget{\n"
"border-image: url(:/newPrefix/denise-bossarte-8rEJiVQk1Vw-unsplash.jpg);\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.generalContainer = QtWidgets.QVBoxLayout()
        self.generalContainer.setObjectName("generalContainer")
        self.menuContainer = QtWidgets.QHBoxLayout()
        self.menuContainer.setObjectName("menuContainer")
        self.adressLine = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.adressLine.setFont(font)
        self.adressLine.setStyleSheet("QLineEdit {\n"
"background-color: black;\n"
"color: orange;\n"
"}")
        self.adressLine.setMaxLength(80)
        self.adressLine.setFrame(True)
        self.adressLine.setCursorPosition(6)
        self.adressLine.setObjectName("adressLine")
        self.menuContainer.addWidget(self.adressLine)
        self.saveBtn = QtWidgets.QPushButton(self.centralwidget)
        self.saveBtn.setStyleSheet("QPushButton{\n"
"background-color:black;\n"
"color:orange;\n"
"}")
        self.saveBtn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/icons8-save-as-96.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.saveBtn.setIcon(icon)
        self.saveBtn.setIconSize(QtCore.QSize(30, 30))
        self.saveBtn.setAutoDefault(False)
        self.saveBtn.setDefault(False)
        self.saveBtn.setFlat(False)
        self.saveBtn.setObjectName("saveBtn")
        self.menuContainer.addWidget(self.saveBtn)
        self.compileBtn = QtWidgets.QPushButton(self.centralwidget)
        self.compileBtn.setStyleSheet("QPushButton{\n"
"background-color:black;\n"
"color:orange;\n"
"}")
        self.compileBtn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/newPrefix/icons8-code-80.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.compileBtn.setIcon(icon1)
        self.compileBtn.setIconSize(QtCore.QSize(30, 30))
        self.compileBtn.setObjectName("compileBtn")
        self.menuContainer.addWidget(self.compileBtn)
        self.closeBtn = QtWidgets.QPushButton(self.centralwidget)
        self.closeBtn.setStyleSheet("QPushButton{\n"
"background-color:black;\n"
"color:orange;\n"
"}")
        self.closeBtn.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/newPrefix/icons8-close-window-96.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.closeBtn.setIcon(icon2)
        self.closeBtn.setIconSize(QtCore.QSize(30, 30))
        self.closeBtn.setObjectName("closeBtn")
        self.menuContainer.addWidget(self.closeBtn)
        self.generalContainer.addLayout(self.menuContainer)
        self.bodyContainer = QtWidgets.QVBoxLayout()
        self.bodyContainer.setContentsMargins(-1, -1, 0, -1)
        self.bodyContainer.setObjectName("bodyContainer")
        self.codeEditor = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.codeEditor.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.codeEditor.setFont(font)
        self.codeEditor.setStyleSheet("QPlainTextEdit {\n"
"background-color: black;\n"
"color: orange;\n"
"\n"
"}")
        self.codeEditor.setObjectName("codeEditor")
        self.bodyContainer.addWidget(self.codeEditor)
        self.bottomContainer = QtWidgets.QHBoxLayout()
        self.bottomContainer.setObjectName("bottomContainer")
        self.logShower = QtWidgets.QTextBrowser(self.centralwidget)
        self.logShower.setEnabled(True)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 165, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 165, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 165, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 165, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 165, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 165, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 165, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 165, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 165, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.logShower.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.logShower.setFont(font)
        self.logShower.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.logShower.setAutoFillBackground(False)
        self.logShower.setStyleSheet("QTextBrowser {\n"
"background-color: black;\n"
"color: orange;\n"
"}")
        self.logShower.setFrameShape(QtWidgets.QFrame.Box)
        self.logShower.setObjectName("logShower")
        self.bottomContainer.addWidget(self.logShower, 0, QtCore.Qt.AlignBottom)
        self.logo = QtWidgets.QLabel(self.centralwidget)
        self.logo.setMaximumSize(QtCore.QSize(100, 100))
        self.logo.setText("")
        self.logo.setPixmap(QtGui.QPixmap(":/newPrefix/icon_1.png"))
        self.logo.setScaledContents(True)
        self.logo.setObjectName("logo")
        self.bottomContainer.addWidget(self.logo)
        self.bodyContainer.addLayout(self.bottomContainer)
        self.generalContainer.addLayout(self.bodyContainer)
        self.horizontalLayout_2.addLayout(self.generalContainer)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.adressLine.setText(_translate("MainWindow", "SASASA"))
        self.codeEditor.setPlainText(_translate("MainWindow", "asdsadd"))
        self.logShower.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:16pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Ready to work!</p></body></html>"))
import background_rc
